### ISSUE TITLE
error when clearing a line

### ISSUE THREAD

**Issue by oakmac** [imalooney/t3tr0s#39]
Steps to reproduce:

1. Go to [t3tr0s.com](http://t3tr0s.com)
1. Enter "Solo" mode
1. Begin playing and clear a line.
1. See the error below in console and the game is locked :(

![t3tr0s-velocity-error-clearing-line](https://cloud.githubusercontent.com/assets/98485/13721730/d66bbf3a-e7f4-11e5-9e5b-6f26470b9371.png)

**Comment by oakmac** [comment]
This seems to completely break the game. Worth looking at.

cc: @shaunlebron @pgambling @imalooney

**Comment by imalooney** [comment]
i just saw this happen this week. Thought maybe simple upgrade of velocity.js would resolve it...doesn't seem to.

**Comment by oakmac** [comment]
This should be fixed now.

@pgambling - Can we update the site?

**Comment by pgambling** [comment]
Done

**Comment by shaunlebron** [comment]
thanks guys, this makes me happy.  we need to play this again when we're all available.

confirmed the fix:

![tetris](https://zippy.gfycat.com/LivelyHorribleGuppy.gif)
